pref("extensions.ndfdweather.iconsize", "medium");
pref("extensions.ndfdweather.interval", 60);
pref("extensions.ndfdweather.forecastdays", 4);
pref("extensions.ndfdweather.refresh", true);
pref("extensions.ndfdweather.textsize", "large");
pref("extensions.ndfdweather.unittype", "e");
pref("extensions.ndfdweather.zipcode", "");
pref("extensions.ndfdweather.latlon", "0,0");
pref("extensions.ndfdweather.statusbar", true);
